### ISSUE TITLE
Error in Pulse Pulse 40.0.2

### ISSUE THREAD

**Issue by lattetown** [pulsedownloader/pulse-issues#16]
Comment (optional):

Error:
```
Error: net::ERR_CONTENT_LENGTH_MISMATCH
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
```

OS: macOS 10.14

**Comment by lattetown** [comment]
It occurred while downloading Fluffy Audio's Dominus Choir Pro on MacOs Mojave (10.14.6).

**Comment by megahertz** [comment]
It looks like some temporary issue. Please let us know if it occurs again in the latest version of Pulse.
