### ISSUE TITLE
Error in Pulse Pulse 40.0.6-dev.721

### ISSUE THREAD

**Issue by mkruselj** [pulsedownloader/pulse-issues#19]
Comment (optional):

Error:
```
Error: ENOENT: no such file or directory, rename 'C:\Users\EvilDragon\AppData\Local\pulse-updater\pending\temp-Pulse Web Setup 40.0.10-dev.768.exe' -> 'C:\Users\EvilDragon\AppData\Local\pulse-updater\pending\Pulse Web Setup 40.0.10-dev.768.exe'
```

OS: Windows NT 10.0.19041

**Comment by megahertz** [comment]
In most cases, it could be solved by restarting Pulse. If you still have any problems with update, try to install the latest version manually from https://c8q9x5e9.map2.ssl.hwcdn.net/Pulse%20Web%20Setup%2040.0.11.exe
