### ISSUE TITLE
🍎 Feedback v38.0.12

### ISSUE THREAD

**Issue by pumpernickelpl** [pulsedownloader/pulse-issues#2]
Event log:

```
Error: ENOENT: no such file or directory, open '/Users/erickhoffmann/Library/Application Support/Pulse/users/JU8Hoep9RbhOhh237E6CHISIC8f2/token.json'
```

**Comment by emmettcooke** [comment]
Hi there, could you please try this new version of Pulse and let me know if that works now?

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg
