### ISSUE TITLE
Error in Pulse Pulse 40.0.4

### ISSUE THREAD

**Issue by edwardkort** [pulsedownloader/pulse-issues#26]
Comment (optional):

Error:
```
Error: EPERM: operation not permitted, open 'C:\Users\kort\AppData\Local\pulse-updater\pending\0-temp-Pulse Web Setup 40.0.12.exe'
```

OS: Windows NT 10.0.19042

**Comment by megahertz** [comment]
Sometimes Pulse can't perform self-update.In this case, it's better to install it manually from https://pulsedownloader.com/
