### ISSUE TITLE
🍎 Feedback v38.0.12

### ISSUE THREAD

**Issue by theovosse** [pulsedownloader/pulse-issues#3]
The bloody thing crashes on creating an account. "Super stable"...

And lightweight: it's 273MB.

Go get a better PR team before you fix your useless software

Event log:

```
Error: ENOENT: no such file or directory, open '/Users/theo/Library/Application Support/Pulse/users/46ysW7SRSoXlkmF1t1127pophkl2/token.json'
```

**Comment by emmettcooke** [comment]
Hi there, could you please try this new version of Pulse and let me know if that works now?

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg

**Comment by emmettcooke** [comment]
Sorry new version:

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-prod-38.0.18/Pulse-38.0.18.dmg
