### ISSUE TITLE
🍎 Feedback v38.0.12

### ISSUE THREAD

**Issue by m-r-m-s** [pulsedownloader/pulse-issues#4]
Event log:

```
Error: ENOENT: no such file or directory, open '/Volumes/HDD/.../Library/Application Support/Pulse/users/2PYnDMBQlmbh0Cz8TPu9Pi4YjDz2/token.json'
```

**Comment by emmettcooke** [comment]
Hi there, could you please try this new version of Pulse and let me know if that works now?

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg

**Comment by m-r-m-s** [comment]
Thanks for the update. To clarify. When I first ran pulse, it threw the above error but I was able to use the down loader with no issue. I will try the new version and report back with any issues.

**Comment by emmettcooke** [comment]
Thanks. It appears to be only for new users (sign up process) and that process has been removed so it should be fixed all going well :)

**Comment by m-r-m-s** [comment]
Ok good to know - I just tried the above link and it returned a 404:
https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg

**Comment by emmettcooke** [comment]
https://github.com/pulsedownloader/releases/releases/download/darwin-x64-prod-38.0.18/Pulse-38.0.18.dmg
