### ISSUE TITLE
Error in Pulse Pulse 40.3.12

### ISSUE THREAD

**Issue by Trotew** [pulsedownloader/pulse-issues#42]
Comment (optional):

When I try to download Tokyo Scoring Drums (TSD), it does "preparing" forever and gave the error below.

Error:
```
Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)
```

OS: Windows NT 10.0.22621

**Comment by megahertz** [comment]
Looks like it's a temporary network issue. Let us know if it still occurs.
