### ISSUE TITLE
Error in Pulse Pulse 40.3.8

### ISSUE THREAD

**Issue by thesonicapothecary** [pulsedownloader/pulse-issues#46]
Comment (optional):

Error:
```
Error: The request timed out.
```

OS: macOS 10.16

**Comment by thesonicapothecary** [comment]
Hello Github,

I am trying to work with sound forest from native instruments and it is supposed to connect with IMPULSE. IMPULSE gives me an error message. Are you related to IMPULSE? How do I access native instruments? I don't understand what is happening, please help me.

**Comment by emmettcooke** [comment]
We are not related to IMPULSE - this is the Native Instruments website:

https://www.native-instruments.com/en/

For more support, please contact the company you purchased your software from. Thanks
