### ISSUE TITLE
🍎 Feedback v38.0.15

### ISSUE THREAD

**Issue by gliljas** [pulsedownloader/pulse-issues#5]
Event log:

```
Error: ENOENT: no such file or directory, open '/Users/gunnar/Library/Application Support/Pulse/users/5oj6yzNBDZN6ywga9okwbGsBVbH2/token.json'
```

**Comment by emmettcooke** [comment]
Hi there, could you please try this new version of Pulse and let me know if that works now?

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg

**Comment by gliljas** [comment]
It does!

**Comment by emmettcooke** [comment]
Great thanks :)
