### ISSUE TITLE
🍎 Feedback v38.0.15

### ISSUE THREAD

**Issue by hujairi-zz** [pulsedownloader/pulse-issues#7]
Event log:

```
Error: ENOENT: no such file or directory, open '/Users/hasanhujairi/Library/Application Support/Pulse/users/x5cKCbrerMh9q5iwr1kbmeNdvCy1/token.json'
```

**Comment by emmettcooke** [comment]
Hi there, could you please try this new version of Pulse and let me know if that works now?

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg

**Comment by emmettcooke** [comment]
Sorry new version

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-prod-38.0.18/Pulse-38.0.18.dmg
