### ISSUE TITLE
🍎 Feedback v38.0.15

### ISSUE THREAD

**Issue by daveynight** [pulsedownloader/pulse-issues#8]
The program crashed on the registration page. I forget whether I was tabbing thru the form or whether I clicked submit before it crashed. Also, the "Paste your key here" field doesn't accept the paste command and there's no option for it in the menus.

Event log:

```
Error: ENOENT: no such file or directory, open '/Users/shindig/Library/Application Support/Pulse/users/Fl1OW9gpoWT3xvcmQumR70nwWaI3/token.json'
```

**Comment by emmettcooke** [comment]
Hi there, thank you for submitting this bug report. We are in the process of investigating and hope to release a new version this week which may resolve this issue

**Comment by emmettcooke** [comment]
Hi there, could you please try this new version of Pulse and let me know if that works now?

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg

**Comment by emmettcooke** [comment]
Sorry new version

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-prod-38.0.18/Pulse-38.0.18.dmg
