### ISSUE TITLE
🍎 Feedback v38.0.17-dev.482

### ISSUE THREAD

**Issue by redpola** [pulsedownloader/pulse-issues#9]
What happened:

Opened Pulse.app for first time. Registered. Saw an obscure error message so it wasn't clear whether my account had been created. Closed app. On website requested password reset. Reopened App. Attempted to login.

Event log:

```
Error: ENOENT: no such file or directory, open '/Users/neil/Library/Application Support/Pulse/users/ANsKPw7s3PRoonRaZ4rlAGyE04F2/token.json'
```

**Comment by emmettcooke** [comment]
Hi there, could you please try this new version of Pulse and let me know if that works now?

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-dev-38.0.17-dev.488/Pulse-38.0.17-dev.488.dmg

**Comment by emmettcooke** [comment]
Sorry new version

https://github.com/pulsedownloader/releases/releases/download/darwin-x64-prod-38.0.18/Pulse-38.0.18.dmg

**Comment by redpola** [comment]
Uh, I can't reset my account to before onboarding to test this in the same way. What change was committed that you think fixed the problem?

**Comment by redpola** [comment]
Uh, ok, I see that your source code isn't publicly available and you're only using github for tracking without all the nice change management integration.

**Comment by emmettcooke** [comment]
Yes that's correct, its not publicly available. We have tested the issue further however and believe its now been resolved. If you do come across anything else please do let us know :)
